////
////  MessagesViewController.swift
////  MJournal-iMessage
////
////  Created by Michael Nikolaev on 17.09.16.
////  Copyright © 2016 Ocode. All rights reserved.
////
//
//import UIKit
//import Messages
//
//class MessagesViewController: MSMessagesAppViewController, UICollectionViewDelegate, UICollectionViewDataSource {
//    
//    @IBOutlet weak var sheduleCollectionView: UICollectionView!
//    @IBOutlet weak var titleLabel: UILabel!
//    
//    override func viewDidLoad() {
//        super.viewDidLoad()
//        // Do any additional setup after loading the view.
//        
//        sheduleCollectionView.delegate = self
//        sheduleCollectionView.dataSource = self
//        
//        titleLabel.font = UIFont.appSemiBoldFont()
//        
//    }
//    
//    func numberOfSections(in collectionView: UICollectionView) -> Int {
//        return 1
//    }
//    
//    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
//        return 1
//    }
//    
//    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
//        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "sheduleCell", for: indexPath) as? iMSheduleCollectionViewCell
//        cell?.dayNumber = Time.getDay()
//        return cell!
//    }
//    
//    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
//        
//        replaceRange
//            if let cell = collectionView.cellForItem(at: indexPath) as? iMSheduleCollectionViewCell {
//                let renderer = UIGraphicsImageRenderer(size: cell.bounds.size)
//                let image = renderer.image { ctx in
//                    cell.drawHierarchy(in: cell.bounds, afterScreenUpdates: true)
//                }
//                layout.image = image
//                layout.caption = "Такие дела"
//                let message = MSMessage()
//                message.layout = layout
//                conversation.insert(message, completionHandler: nil)
//            }
//        }
//    }
//    
//    
//    
//    // MARK: - Conversation Handling
//    
//    override func willBecomeActive(with conversation: MSConversation) {
//        // Called when the extension is about to move from the inactive to active state.
//        // This will happen when the extension is about to present UI.
//        
//        // Use this method to configure the extension and restore previously stored state.
//    }
//    
//    override func didResignActive(with conversation: MSConversation) {
//        // Called when the extension is about to move from the active to inactive state.
//        // This will happen when the user dissmises the extension, changes to a different
//        // conversation or quits Messages.
//        
//        // Use this method to release shared resources, save user data, invalidate timers,
//        // and store enough state information to restore your extension to its current state
//        // in case it is terminated later.
//    }
//    
//    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
//        // Called when a message arrives that was generated by another instance of this
//        // extension on a remote device.
//        
//        // Use this method to trigger UI updates in response to the message.
//    }
//
//    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
//        // Called when the user taps the send button.
//    }
//    
//    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
//        // Called when the user deletes the message without sending it.
//        
//        // Use this to clean up state related to the deleted message.
//    }
//    
//    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
//        // Called before the extension transitions to a new presentation style.
//        
//        // Use this method to prepare for the change in presentation style.
//    }
//    
//    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
//        // Called after the extension transitions to a new presentation style.
//        
//        // Use this method to finalize any behaviors associated with the change in presentation style.
//    }
//    
//
